<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Part extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Part_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','part/tbl_part_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Part_model->json();
    }

    public function read($id) 
    {
        $row = $this->Part_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_part' => $row->id_part,
		'part' => $row->part,
	    );
            $this->template->load('template','part/tbl_part_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('part'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('part/create_action'),
	    'id_part' => set_value('id_part'),
	    'part' => set_value('part'),
	);
        $this->template->load('template','part/tbl_part_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'part' => $this->input->post('part',TRUE),
	    );

            $this->Part_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('part'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Part_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('part/update_action'),
		'id_part' => set_value('id_part', $row->id_part),
		'part' => set_value('part', $row->part),
	    );
            $this->template->load('template','part/tbl_part_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('part'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_part', TRUE));
        } else {
            $data = array(
		'part' => $this->input->post('part',TRUE),
	    );

            $this->Part_model->update($this->input->post('id_part', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('part'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Part_model->get_by_id($id);

        if ($row) {
            $this->Part_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('part'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('part'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('part', 'part', 'trim|required');

	$this->form_validation->set_rules('id_part', 'id_part', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "tbl_part.xls";
        $judul = "tbl_part";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");
	xlsWriteLabel($tablehead, $kolomhead++, "Part");

	foreach ($this->Part_model->get_all() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
            xlsWriteNumber($tablebody, $kolombody++, $nourut);
	    xlsWriteLabel($tablebody, $kolombody++, $data->part);

	    $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

}

/* End of file Part.php */
/* Location: ./application/controllers/Part.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-05 08:01:44 */
/* http://harviacode.com */