<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_produk_model extends CI_Model
{

    public $table = 'tbl_produk';
    public $id = 'id_part_number';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_part_number,part_number,part_name,size,type,part,material,weight_core,weight_casting,weight_yield,weight_mach');
        $this->datatables->from('tbl_produk');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_produk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('data_produk/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-xs'))." 
            " .anchor(site_url('data_produk/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-primary btn-xs'))." 
                ".anchor(site_url('data_produk/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-xs" onclick="javasciprt: return confirm(\'Are You Sure ?\')"') //ingin memberikan if pada button delete
               , 'id_part_number');         
                
                
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_part_number', $q);
	$this->db->or_like('part_number', $q);
	$this->db->or_like('part_name', $q);
	$this->db->or_like('size', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('part', $q);
	$this->db->or_like('material', $q);
	$this->db->or_like('weight_core', $q);
	$this->db->or_like('weight_casting', $q);
	$this->db->or_like('weight_yield', $q);
	$this->db->or_like('weight_mach', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_part_number', $q);
	$this->db->or_like('part_number', $q);
	$this->db->or_like('part_name', $q);
	$this->db->or_like('size', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('part', $q);
	$this->db->or_like('material', $q);
	$this->db->or_like('weight_core', $q);
	$this->db->or_like('weight_casting', $q);
	$this->db->or_like('weight_yield', $q);
	$this->db->or_like('weight_mach', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_produk_model.php */
/* Location: ./application/models/Data_produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-05 07:30:33 */
/* http://harviacode.com */