<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Wo_detail_model extends CI_Model
{

    public $table = 'tbl_wo_detail';
    public $id = 'id_wo_detail';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_wo_detail,no_wo_detail,type_wo,status_wo,part_number_wo,part_name_wo,part_wo,size_wo,plan_wo,actual_wo,ok_wo,ng_wo,deskripsi_wo');
        $this->datatables->from('tbl_wo_detail');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_wo_detail.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('wo_detail/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-primary btn-xs'))." 
            ".anchor(site_url('wo_detail/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-xs'))." 
                ".anchor(site_url('wo_detail/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-xs" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_wo_detail');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_wo_detail', $q);
	$this->db->or_like('no_wo_detail', $q);
	$this->db->or_like('type_wo', $q);
	$this->db->or_like('status_wo', $q);
	$this->db->or_like('part_number_wo', $q);
	$this->db->or_like('part_name_wo', $q);
	$this->db->or_like('part_wo', $q);
	$this->db->or_like('size_wo', $q);
	$this->db->or_like('plan_wo', $q);
	$this->db->or_like('actual_wo', $q);
	$this->db->or_like('ok_wo', $q);
	$this->db->or_like('ng_wo', $q);
	$this->db->or_like('deskripsi_wo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_wo_detail', $q);
	$this->db->or_like('no_wo_detail', $q);
	$this->db->or_like('type_wo', $q);
	$this->db->or_like('status_wo', $q);
	$this->db->or_like('part_number_wo', $q);
	$this->db->or_like('part_name_wo', $q);
	$this->db->or_like('part_wo', $q);
	$this->db->or_like('size_wo', $q);
	$this->db->or_like('plan_wo', $q);
	$this->db->or_like('actual_wo', $q);
	$this->db->or_like('ok_wo', $q);
	$this->db->or_like('ng_wo', $q);
	$this->db->or_like('deskripsi_wo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Wo_detail_model.php */
/* Location: ./application/models/Wo_detail_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-15 03:33:41 */
/* http://harviacode.com */